# version: "2"

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: snapbox
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
